3924 schema
untangle/mfw_schema pull request #56
Opened 2023-12-04 17:05 UTC by naveen-gowda-arista

2023-12-07 17:50 UTC, Utkarsh51 commented on v1/quota_manager/__pycache__/validate_quota_manager.cpython-39.pyc
I don;t think this file should be a prt of the PR

2023-12-07 18:06 UTC, Utkarsh51 requested changes

2023-12-07 18:06 UTC, Utkarsh51 commented on .vscode/tasks.json
> +            "command": "./validate.py Quota Manager v1/quota_manager/test_schema.json v1/quota_manager/quota_manager_test.json",
the argument Quota Manager should be the key defined validate.py

2023-12-07 18:14 UTC, Utkarsh51 requested changes

2023-12-07 18:14 UTC, Utkarsh51 commented on .vscode/tasks.json
> -    ],
Why the comma is removed?

2023-12-11 05:45 UTC, naveen-gowda-arista commented on v1/quota_manager/__pycache__/validate_quota_manager.cpython-39.pyc
Ok. Removed it.

2023-12-11 05:45 UTC, naveen-gowda-arista commented on .vscode/tasks.json
> -    ],
Looks like typo. Fixed it.

2023-12-11 05:45 UTC, naveen-gowda-arista commented on .vscode/tasks.json
> +            "command": "./validate.py Quota Manager v1/quota_manager/test_schema.json v1/quota_manager/quota_manager_test.json",
Fixed it.

2023-12-11 15:03 UTC, Utkarsh51 requested changes

2023-12-11 15:03 UTC, Utkarsh51 commented on .vscode/tasks.json
> +            "command": "./validate.py quota_manage v1/quota_manager/test_schema.json v1/quota_manager/quota_manager_test.json",
this still would give an error "quota_manage" doesn't match with what is defined in validate.py

2023-12-12 05:19 UTC, naveen-gowda-arista commented on .vscode/tasks.json
> +            "command": "./validate.py quota_manage v1/quota_manager/test_schema.json v1/quota_manager/quota_manager_test.json",
I hace fixed and ran the same command from .vscode and ran the test...here is the output.
[Is there any other way to test this apart from this method]


~/untangle/mfw_schema @us277.sjc> ./validate.py quota_manager v1/quota_manager/test_schema.json v1/quota_manager/quota_manager_test.json
=== START OF MODULE TEST: <module 'v1.quota_manager.validate_quota_manager' from '/home/naveen.gowda/untangle/mfw_schema/v1/quota_manager/validate_quota_manager.py'> ===

test_base_id_uniqueness (v1.quota_manager.validate_quota_manager.TestQuotaManager)
Tests that the base id's (e.g., quota/id or configuration/id) are all only used once at that level. That ... ok
test_configuration_ids_in_quota_rules (v1.quota_manager.validate_quota_manager.TestQuotaManager)
Tests that any configuration id's under quota rule's actions (but not the other way around) ... ok
test_exceed_action_ids_in_rules (v1.quota_manager.validate_quota_manager.TestQuotaManager)
Tests that any exceed action id's under rules exist in exceed_actions (but not the other way around) ... ok
test_valid_ids (v1.quota_manager.validate_quota_manager.TestQuotaManager)
Testing that each quota_manager lists configuration's id is a valid uuid ... ok
{'configurations': {'orphans': ['1c60f45e-919b-11ee-b9d1-0242ac120002']}, 'exceed_actions': {'orphans': ['5120fbfc-919a-11ee-b9d1-0242ac120002']}, 'rules': {}, 'rule_conditions': {}, 'rule_action': {}}

----------------------------------------------------------------------
Ran 4 tests in 0.009s

OK
=== END OF MODULE TEST: <module 'v1.quota_manager.validate_quota_manager' from '/home/naveen.gowda/untangle/mfw_schema/v1/quota_manager/validate_quota_manager.py'> ===

~/untangle/mfw_schema @us277.sjc>

2023-12-12 08:21 UTC, Utkarsh51 approved these changes
LGTM

2023-12-14 05:30 UTC, merged