Mfw 5903 -  added settings schema  configurations
untangle/mfw_schema pull request #73
Opened 2024-11-26 11:24 UTC by vishal-malji

2024-11-26 13:07 UTC, Utkarsh51 requested changes
Add Vscode task for this

2024-11-28 09:47 UTC, Utkarsh51 approved these changes

2024-11-28 10:48 UTC, Utkarsh51 commented on v1/bypass/bypass_test.json
> +                "ruleId": "9c9b22c1-3eb7-4218-ac46-de5d2eb4dc18"
log property is missing

2024-11-28 10:48 UTC, Utkarsh51 commented on v1/bypass/bypass_schema.json
> +                },
log property is missing

2024-11-28 10:48 UTC, Utkarsh51 commented on v1/bypass/bypass_schema.json
> +                "op": {
port_protocol is missing from condition schema

2024-11-28 13:16 UTC, vishal-malji commented on v1/bypass/bypass_test.json
> +                "ruleId": "9c9b22c1-3eb7-4218-ac46-de5d2eb4dc18"
added

2024-11-28 13:16 UTC, vishal-malji commented on v1/bypass/bypass_schema.json
> +                "op": {
added

2024-11-28 13:16 UTC, vishal-malji commented on v1/bypass/bypass_schema.json
> +                },
added

2024-11-28 13:48 UTC, AlistairJohnParker approved these changes

2024-12-02 15:16 UTC, Utkarsh51 approved these changes

2024-12-02 15:48 UTC, merged