MFW-5938 added dns filter schema
untangle/mfw_schema pull request #74
Opened 2024-12-09 13:20 UTC by vishal-malji

2024-12-09 15:21 UTC, AlistairJohnParker commented on v1/dns_filter/dnsfilter_test.json
> +            {
Could add some more variations eg. "flagged": false

2024-12-09 15:28 UTC, AlistairJohnParker commented on v1/dns_filter/validate_dnsfilter.py
> +    def test_validate_schema(self):
This seems unnecessary

2024-12-09 15:32 UTC, AlistairJohnParker submitted a review, later dismissed
DNS test schema is minimal.

2024-12-10 05:13 UTC, vishal-malji commented on v1/dns_filter/dnsfilter_test.json
> +            {
Ok will add

2024-12-10 06:47 UTC, Utkarsh51 commented on .vscode/tasks.json
> +            "label": "Test DNSFilter",
I would suggest a space between DNS and Filter.
Maybe we can define a convension how are we going to label the tasks since it doesn't seem to follow any convension.

2024-12-10 06:59 UTC, Utkarsh51 commented on v1/dns_filter/dnsfilter_schema.json
> +{
This should be updated

2024-12-10 06:59 UTC, Utkarsh51 commented on v1/dns_filter/dnsfilter_test.json
> +        "logging": {
Logging should be per item?

2024-12-10 07:04 UTC, Utkarsh51 requested changes
Update the schema

2024-12-10 08:57 UTC, vishal-malji commented on .vscode/tasks.json
> +            "label": "Test DNSFilter",
ok

2024-12-10 09:13 UTC, vishal-malji commented on v1/dns_filter/dnsfilter_test.json
> +        "logging": {
added

2024-12-10 15:06 UTC, vishal-malji commented
> Update the schema
done
cc @Utkarsh51

2024-12-11 10:57 UTC, Utkarsh51 approved these changes

2024-12-11 13:59 UTC, AlistairJohnParker approved these changes

2024-12-12 06:42 UTC, merged